# Generated by Django 3.0.3 on 2020-03-08 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SelectVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_id', models.CharField(max_length=10)),
                ('compassion', models.BooleanField(default=False)),
                ('surface_acting', models.BooleanField(default=False)),
                ('deep_acting', models.BooleanField(default=False)),
                ('affective_commitment', models.BooleanField(default=False)),
                ('task_complexity', models.BooleanField(default=False)),
            ],
        ),
    ]
