# Generated by Django 3.0.3 on 2020-03-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10)),
                ('employee_pw', models.CharField(max_length=16)),
                ('employee_coname', models.CharField(max_length=10)),
                ('co_id', models.CharField(max_length=10)),
            ],
        ),
    ]
