# Generated by Django 3.0.3 on 2020-04-08 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200407_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='company_id',
        ),
    ]
