# Generated by Django 3.0.3 on 2020-03-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200316_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='affective_commitment_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='affective_commitment_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='compassion_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='compassion_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='deep_acting_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='deep_acting_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='surface_acting_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='surface_acting_2',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='task_complexity_1',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='task_complexity_2',
            field=models.IntegerField(null=True),
        ),
    ]
